In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('data/zeel/ZEEL (20240930093400000 _ 20240925105700000).csv')
data

Date    Open    High  \
0     Wed Sep 25 2024 10:57:00 GMT+0530 (India Stand...  128.35  128.36   
1     Wed Sep 25 2024 10:58:00 GMT+0530 (India Stand...  128.34  128.40   
2     Wed Sep 25 2024 10:59:00 GMT+0530 (India Stand...  128.37  128.39   
3     Wed Sep 25 2024 11:00:00 GMT+0530 (India Stand...  128.34  128.35   
4     Wed Sep 25 2024 11:01:00 GMT+0530 (India Stand...  128.35  128.40   
...                                                 ...     ...     ...   
1018  Fri Sep 27 2024 15:25:00 GMT+0530 (India Stand...  135.14  135.38   
1019  Fri Sep 27 2024 15:26:00 GMT+0530 (India Stand...  135.15  135.37   
1020  Fri Sep 27 2024 15:27:00 GMT+0530 (India Stand...  135.15  135.30   
1021  Fri Sep 27 2024 15:28:00 GMT+0530 (India Stand...  135.24  135.30   
1022  Fri Sep 27 2024 15:29:00 GMT+0530 (India Stand...  135.24  135.25   

         Low   Close  Jaw ‌Alligator‌  Teeth ‌Alligator  Lips ‌Alligator  \
0     128.27  128.34           127.57            127.87           128.47   
1     128.32  128.39           127.58            127.96           128.44   
2     128.30  128.34           127.60            128.06           128.42   
3     128.30  128.35           127.61            128.14           128.41   
4     128.30  128.35           127.65            128.18           128.39   
...      ...     ...              ...               ...              ...   
1018  135.05  135.17           135.74            135.88           135.50   
1019  135.10  135.10           135.75            135.88           135.45   
1020  135.06  135.30           135.76            135.88           135.40   
1021  135.05  135.10           135.77            135.87           135.36   
1022  135.05  135.15           135.78            135.83           135.32   

         MA5    MA15    Volume  Volume Change Percentage  
0     128.42  128.54    8697.0                    -68.27  
1     128.38  128.55   18923.0                    -85.49  
2     128.36  128.54   17725.0                    -63.08  
3     128.35  128.52    4863.0                    -95.12  
4     128.35  128.49   10833.0                    -74.49  
...      ...     ...       ...                       ...  
1018  135.27  135.70   96944.0                    -58.69  
1019  135.23  135.64  123132.0                    -33.40  
1020  135.23  135.61  119850.0                    -36.70  
1021  135.17  135.55  122398.0                    -57.00  
1022  135.16  135.50  141743.0                    -35.77  

[1023 rows x 12 columns]

In [3]:
data.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Jaw ‌Alligator‌',
       'Teeth ‌Alligator', 'Lips ‌Alligator', 'MA5', 'MA15', 'Volume',
       'Volume Change Percentage'],
      dtype='object')

In [4]:
data = data.to_numpy()
data = data[:, 1:] # removing the dates column

In [5]:
print(data.shape)
data

(1023, 11)


array([[128.35, 128.36, 128.27, ..., 128.54, 8697.0, -68.27],
       [128.34, 128.4, 128.32, ..., 128.55, 18923.0, -85.49],
       [128.37, 128.39, 128.3, ..., 128.54, 17725.0, -63.08],
       ...,
       [135.15, 135.3, 135.06, ..., 135.61, 119850.0, -36.7],
       [135.24, 135.3, 135.05, ..., 135.55, 122398.0, -57.0],
       [135.24, 135.25, 135.05, ..., 135.5, 141743.0, -35.77]],
      dtype=object)

In [6]:
X, y = [], []

In [7]:
last_candles_count = 5
next_candles_count = 3

for idx, row in enumerate(data[last_candles_count-1 : 
    -(last_candles_count + next_candles_count)]):
    idx = idx + last_candles_count
    first_open = data[idx-last_candles_count][0]
    first_jaw = data[idx-last_candles_count][4]
    first_lip = data[idx-last_candles_count][6]
    first_teeth = data[idx-last_candles_count][5]
    first_ma5 = data[idx-last_candles_count][7]
    first_ma15 = data[idx-last_candles_count][8]
    first_volumn = data[idx-last_candles_count][9]
    first_volumn_change = data[idx-last_candles_count][10]
    last_candles = []
    for candle in data[idx-last_candles_count : idx]:
        temp = []
        temp.append(round(candle[0]-first_open, 2))
        temp.append(round(candle[1]-first_open, 2))
        temp.append(round(candle[2]-first_open, 2))
        temp.append(round(candle[3]-first_open, 2))
        temp.append(round(candle[4]-first_jaw, 2))
        temp.append(round(candle[5]-first_teeth, 2))
        temp.append(round(candle[6]-first_lip, 2))
        temp.append(round(candle[7]-first_ma5, 2))
        temp.append(round(candle[8]-first_ma15, 2))
        temp.append(round(candle[9]-first_volumn, 2))
        temp.append(round(candle[10]-first_volumn_change, 2))
        # for param in candle:
        #     temp.append(round(param-first_open, 2))
        last_candles.append(temp)
    X.append(last_candles)
    next_candles = []
    for candle in data[idx: idx+next_candles_count]:
        temp = []
        temp.append(round(candle[0]-first_open, 2))
        # temp.append(round(candle[1]-first_open, 2))
        # temp.append(round(candle[2]-first_open, 2))
        # temp.append(round(candle[3]-first_open, 2))
        # temp.append(round(candle[4]-first_jaw, 2))
        # temp.append(round(candle[5]-first_teeth, 2))
        # temp.append(round(candle[6]-first_lip, 2))
        # temp.append(round(candle[7]-first_ma5, 2))
        # temp.append(round(candle[8]-first_ma15, 2))
        # temp.append(round(candle[9]-first_volumn, 2))
        # temp.append(round(candle[10]-first_volumn_change, 2))
        
        # for param in candle:
        #     temp.append(round(param-first_open, 2))
        next_candles.append(temp)
    y.append(next_candles)

In [10]:
X[0]

[[0.0, 0.01, -0.08, -0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [-0.01, 0.05, -0.03, 0.04, 0.01, 0.09, -0.03, -0.04, 0.01, 10226.0, -17.22],
 [0.02, 0.04, -0.05, -0.01, 0.03, 0.19, -0.05, -0.06, 0.0, 9028.0, 5.19],
 [-0.01, 0.0, -0.05, 0.0, 0.04, 0.27, -0.06, -0.07, -0.02, -3834.0, -26.85],
 [0.0, 0.05, -0.05, 0.0, 0.08, 0.31, -0.08, -0.07, -0.05, 2136.0, -6.22]]

In [11]:
y[0]

[[0.03], [0.15], [0.01]]

In [12]:
print("data:\n", data[:8])
print("\nX:", X[0])
print("\ny:", y[0])

data:
 [[128.35 128.36 128.27 128.34 127.57 127.87 128.47 128.42 128.54 8697.0
  -68.27]
 [128.34 128.4 128.32 128.39 127.58 127.96 128.44 128.38 128.55 18923.0
  -85.49]
 [128.37 128.39 128.3 128.34 127.6 128.06 128.42 128.36 128.54 17725.0
  -63.08]
 [128.34 128.35 128.3 128.35 127.61 128.14 128.41 128.35 128.52 4863.0
  -95.12]
 [128.35 128.4 128.3 128.35 127.65 128.18 128.39 128.35 128.49 10833.0
  -74.49]
 [128.38 128.5 128.24 128.49 127.68 128.22 128.38 128.38 128.48 53924.0
  33.19]
 [128.5 128.58 128.32 128.32 127.71 128.27 128.38 128.37 128.46 70777.0
  291.9]
 [128.36 128.6 128.36 128.6 127.75 128.33 128.39 128.42 128.47 75204.0
  33.82]]

X: [[0.0, 0.01, -0.08, -0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [-0.01, 0.05, -0.03, 0.04, 0.01, 0.09, -0.03, -0.04, 0.01, 10226.0, -17.22], [0.02, 0.04, -0.05, -0.01, 0.03, 0.19, -0.05, -0.06, 0.0, 9028.0, 5.19], [-0.01, 0.0, -0.05, 0.0, 0.04, 0.27, -0.06, -0.07, -0.02, -3834.0, -26.85], [0.0, 0.05, -0.05, 0.0, 0.08, 0.31, -0.08, -0.07, 

In [13]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Reshape, InputLayer, Flatten

In [14]:
X = tf.constant(X, dtype=tf.float32)
y = tf.constant(y, dtype=tf.float32)
X, y

(<tf.Tensor: shape=(1011, 5, 11), dtype=float32, numpy=
 array([[[ 0.00000e+00,  1.00000e-02, -8.00000e-02, ...,  0.00000e+00,
           0.00000e+00,  0.00000e+00],
         [-1.00000e-02,  5.00000e-02, -3.00000e-02, ...,  1.00000e-02,
           1.02260e+04, -1.72200e+01],
         [ 2.00000e-02,  4.00000e-02, -5.00000e-02, ...,  0.00000e+00,
           9.02800e+03,  5.19000e+00],
         [-1.00000e-02,  0.00000e+00, -5.00000e-02, ..., -2.00000e-02,
          -3.83400e+03, -2.68500e+01],
         [ 0.00000e+00,  5.00000e-02, -5.00000e-02, ..., -5.00000e-02,
           2.13600e+03, -6.22000e+00]],
 
        [[ 0.00000e+00,  6.00000e-02, -2.00000e-02, ...,  0.00000e+00,
           0.00000e+00,  0.00000e+00],
         [ 3.00000e-02,  5.00000e-02, -4.00000e-02, ..., -1.00000e-02,
          -1.19800e+03,  2.24100e+01],
         [ 0.00000e+00,  1.00000e-02, -4.00000e-02, ..., -3.00000e-02,
          -1.40600e+04, -9.63000e+00],
         [ 1.00000e-02,  6.00000e-02, -4.00000e-02, ..., -6.0

In [15]:
model = Sequential()
model.add(LSTM(200, input_shape=(5, 11), activation='relu', return_sequences=True))
# model.add(Dropout(0.2))
model.add(LSTM(150, activation='relu'))
# model.add(Dropout(0.2))
model.add(Dense(33))
model.add(Reshape((3, 11)))
model.compile(optimizer='adam', loss='mse')

/Users/anodic_passion/PycharmProjects/108decillion/.venv/lib/python3.11/site-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [16]:
model = Sequential(
    [
        Flatten(input_shape=(5, 11)),  # Flatten the 3D input to 2D
        Dense(1000, activation='relu'),
        Dense(600, activation='relu'),
        Dropout(0.2),
        Dense(400, activation='relu'),
        Dense(150, activation='relu'),
        Dropout(0.2),
        Dense(33, activation='relu'),
        Reshape((3, 11))
        # Dense(55, activation='relu'),
        # Dense(3, activation='relu'),
    ]
)

model.compile(optimizer='SGD', loss='mae')

/Users/anodic_passion/PycharmProjects/108decillion/.venv/lib/python3.11/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
history = model.fit(X, y, epochs=1000, batch_size=32, validation_split=0.2)

Epoch 1/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 368.5769 - val_loss: 0.1671
Epoch 2/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3771 - val_loss: 0.1671
Epoch 3/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3630 - val_loss: 0.1671
Epoch 4/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3645 - val_loss: 0.1671
Epoch 5/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3713 - val_loss: 0.1671
Epoch 6/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3461 - val_loss: 0.1671
Epoch 7/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3646 - val_loss: 0.1671
Epoch 8/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3641 - val_loss: 0.1671
Epoch 9/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3719 - val_loss: 0.1671
Epoch 10/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3530 - val_loss: 0.1671
Epoch 11/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3782 - val_loss: 0.1671
Epoch 12/1000
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/st

In [ ]:
X.shape, y.shape

In [ ]:
X_test = [[0.0, 0.01, -0.08, -0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [-0.01, 0.05, -0.03, 0.04, 0.01, 0.09, -0.03, -0.04, 0.01, 10226.0, -17.22], [0.02, 0.04, -0.05, -0.01, 0.03, 0.19, -0.05, -0.06, 0.0, 9028.0, 5.19], [-0.01, 0.0, -0.05, 0.0, 0.04, 0.27, -0.06, -0.07, -0.02, -3834.0, -26.85], [0.0, 0.05, -0.05, 0.0, 0.08, 0.31, -0.08, -0.07, -0.05, 2136.0, -6.22]]
y_test = [[0.03, 0.15, -0.11, 0.14, 0.11, 0.35, -0.09, -0.04, -0.06, 45227.0, 101.46], [0.15, 0.23, -0.03, -0.03, 0.14, 0.4, -0.09, -0.05, -0.08, 62080.0, 360.17], [0.01, 0.25, 0.01, 0.25, 0.18, 0.46, -0.08, 0.0, -0.07, 66507.0, 102.09]]
y_pred = model.predict(X[0:1])
y_pred, y_test

In [ ]:
import matplotlib.pyplot as plt

# Example for the first feature (e.g., Close price)
plt.plot(y_test, label='Actual Close')
plt.plot(y_pred, label='Predicted Close')
plt.legend()
plt.show()