In [16]:
from indicators.syncind import SyncInd
from indicators.classic import SMA, Alligator, SmoothMA, RSI, MACD
import numpy as np
from fyers_apiv3 import fyersModel
import time, datetime
client_id = "ZHQ4IJL7TI-100"
with open("access_token", "r") as f:
    access_token = f.read()

fyers = fyersModel.FyersModel(client_id=client_id, is_async=False, token=access_token, log_path="")

In [17]:
date_today = datetime.datetime.now().strftime("%Y-%m-%d")
date_100_p = (datetime.datetime.now() - datetime.timedelta(days=100)).strftime("%Y-%m-%d")
date_today, date_100_p

('2024-11-20', '2024-08-12')

In [18]:
response = fyers.history(data={"symbol": "NSE:ZEEL-EQ",
                                "resolution": "1",
                                 "date_format": "1",
                                "range_from": date_100_p,
                                "range_to": date_today,
                                "cont_flag": "1"
                                })

len(response['candles']), response

(25560,
 {'candles': [[1723434300, 137.54, 138.16, 136.56, 136.88, 217704],
   [1723434360, 136.84, 137.22, 136.7, 137.22, 69847],
   [1723434420, 137.04, 137.04, 136.3, 136.5, 131712],
   [1723434480, 136.5, 136.5, 135.92, 136.27, 123915],
   [1723434540, 136.2, 136.47, 136.06, 136.27, 53732],
   [1723434600, 136.27, 136.49, 135.81, 136.36, 64314],
   [1723434660, 136.36, 136.64, 136.36, 136.5, 40702],
   [1723434720, 136.5, 137, 136.5, 136.99, 39541],
   [1723434780, 137, 137.25, 136.82, 137.16, 41777],
   [1723434840, 137.16, 137.17, 136.82, 137.1, 44930],
   [1723434900, 137.1, 137.6, 137.1, 137.42, 90102],
   [1723434960, 137.44, 137.5, 137.15, 137.18, 44119],
   [1723435020, 137.18, 137.19, 136.81, 137.11, 62343],
   [1723435080, 137.11, 137.11, 136.63, 136.8, 54696],
   [1723435140, 136.81, 136.96, 136.71, 136.71, 42716],
   [1723435200, 136.8, 137.2, 136.72, 137.19, 18744],
   [1723435260, 137.2, 137.39, 137.12, 137.19, 24431],
   [1723435320, 137.12, 137.12, 136.71, 136.84, 44

In [19]:
candles = np.array(response['candles'])
type(candles), candles

(numpy.ndarray,
 array([[1.72343430e+09, 1.37540000e+02, 1.38160000e+02, 1.36560000e+02,
         1.36880000e+02, 2.17704000e+05],
        [1.72343436e+09, 1.36840000e+02, 1.37220000e+02, 1.36700000e+02,
         1.37220000e+02, 6.98470000e+04],
        [1.72343442e+09, 1.37040000e+02, 1.37040000e+02, 1.36300000e+02,
         1.36500000e+02, 1.31712000e+05],
        ...,
        [1.73201022e+09, 1.22910000e+02, 1.22940000e+02, 1.22740000e+02,
         1.22850000e+02, 2.18057000e+05],
        [1.73201028e+09, 1.22800000e+02, 1.22870000e+02, 1.22700000e+02,
         1.22750000e+02, 1.00029000e+05],
        [1.73201034e+09, 1.22800000e+02, 1.22850000e+02, 1.22400000e+02,
         1.22400000e+02, 1.02769000e+05]]))

In [20]:
sync = SyncInd( SMA(5), 
                SMA(15), 
                Alligator(jaw_offset=1, lips_offset=1, teeth_offset=1),
                SmoothMA(7),
                RSI(14),
                MACD(),
              )
                
for c in candles:
    sync.append(c)


In [21]:
sync.last_candle().shape

(16,)

In [32]:
sync.last_candle()

array([1732010368.0, 122.80000305175781, 122.8499984741211,
       122.4000015258789, 122.4000015258789, 102769.0, 122.67, 122.56,
       122.7, 122.68, 122.7, 122.63, 42.71525243454722, -0.05, -0.06,
       0.01], dtype=object)

In [33]:
sync.data()[-2]

array([1732010368.0, 122.80000305175781, 122.8499984741211,
       122.4000015258789, 122.4000015258789, 102769.0, 122.79, 122.53,
       122.71, 122.69, 122.72, 122.67, 42.71525243454722, -0.02, -0.06,
       0.04], dtype=object)