In [2]:
from indicators.syncind import SyncInd
from indicators.classic import SMA, Alligator, SmoothMA, RSI, MACD, ATR, WMA, EMA, RMA
from indicators.candle import OHLC
import numpy as np
from fyers_apiv3 import fyersModel
import time, datetime
client_id = "ZHQ4IJL7TI-100"
with open("access_token", "r") as f:
    access_token = f.read()

fyers = fyersModel.FyersModel(client_id=client_id, is_async=False, token=access_token, log_path="")

In [3]:
date_today = datetime.datetime.now().strftime("%Y-%m-%d")
date_100_p = (datetime.datetime.now() - datetime.timedelta(days=100)).strftime("%Y-%m-%d")
date_today, date_100_p

('2024-11-21', '2024-08-13')

In [4]:
response = fyers.history(data={"symbol": "NSE:ZEEL-EQ",
                                "resolution": "1",
                                 "date_format": "1",
                                "range_from": date_100_p,
                                "range_to": date_today,
                                "cont_flag": "1"
                                })

len(response['candles']), response

(25560,
 {'candles': [[1723520700, 136.65, 137.3, 136.49, 137.24, 104552],
   [1723520760, 137.24, 137.24, 136.85, 136.95, 59548],
   [1723520820, 136.95, 137.15, 136.86, 137.05, 45886],
   [1723520880, 137.05, 137.05, 136.85, 136.89, 23903],
   [1723520940, 136.8, 136.89, 136.68, 136.77, 29208],
   [1723521000, 136.77, 136.79, 136.25, 136.3, 40240],
   [1723521060, 136.42, 136.62, 136.32, 136.61, 28461],
   [1723521120, 136.61, 136.95, 136.55, 136.95, 47602],
   [1723521180, 136.95, 136.97, 136.82, 136.94, 12776],
   [1723521240, 136.94, 136.94, 136.7, 136.7, 10933],
   [1723521300, 136.76, 136.93, 136.7, 136.92, 10906],
   [1723521360, 136.85, 136.9, 136.57, 136.64, 24140],
   [1723521420, 136.64, 136.8, 136.59, 136.8, 9005],
   [1723521480, 136.67, 136.91, 136.67, 136.91, 6432],
   [1723521540, 136.93, 137, 136.92, 137, 18301],
   [1723521600, 136.99, 137, 136.79, 136.8, 13836],
   [1723521660, 136.8, 136.92, 136.66, 136.67, 51735],
   [1723521720, 136.67, 136.87, 136.67, 136.87, 94

In [5]:
candles = np.array(response['candles'])
type(candles), candles

(numpy.ndarray,
 array([[1.72352070e+09, 1.36650000e+02, 1.37300000e+02, 1.36490000e+02,
         1.37240000e+02, 1.04552000e+05],
        [1.72352076e+09, 1.37240000e+02, 1.37240000e+02, 1.36850000e+02,
         1.36950000e+02, 5.95480000e+04],
        [1.72352082e+09, 1.36950000e+02, 1.37150000e+02, 1.36860000e+02,
         1.37050000e+02, 4.58860000e+04],
        ...,
        [1.73218302e+09, 1.18420000e+02, 1.18450000e+02, 1.18330000e+02,
         1.18350000e+02, 4.36910000e+04],
        [1.73218308e+09, 1.18260000e+02, 1.18330000e+02, 1.18150000e+02,
         1.18150000e+02, 1.52701000e+05],
        [1.73218314e+09, 1.18000000e+02, 1.18000000e+02, 1.17500000e+02,
         1.17990000e+02, 2.65994000e+05]]))

In [11]:
sync = SyncInd( 
                SMA(5),
                SMA(15),
                Alligator()
              )
                
for c in candles:
    sync.append(c)


In [7]:
sync.last_candle().shape

(8,)

In [8]:
sync.last_candle()

array([1732183168.0, 118.0, 118.0, 117.5, 117.98999786376953, 265994.0,
       118.32466666666666, 118.37], dtype=object)

In [9]:
sync.data()[-2]

array([1732183040.0, 118.26000213623047, 118.33000183105469,
       118.1500015258789, 118.1500015258789, 152701.0, 118.43022222222224,
       118.46], dtype=object)

In [ ]:
Super_t = []
s = SuperTrend()
for i in candles:
    Super_t.append(s(OHLC(i)))

In [ ]:
candles[-3:]

In [ ]:
Super_t[-10:]

In [ ]:
Super_t.count(-1)

In [ ]:
len(Super_t)

In [ ]:
X, y = [], []

last_candles_count = 8
next_candles_cound = 3

current_data = sync.data()
for i in current_data[30 + last_candles_count -1 : -(next_candles_cound + 1)]:
    X.append()